import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const styles = readFileSync("src/styles.css", "utf-8");
const indexHtml = readFileSync("index.html", "utf-8");

describe("small mobile responsive CSS", () => {
  it("uses a fixed mobile top bar with safe-area paint and hero offset", () => {
    expect(indexHtml).toContain('name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"');
    expect(styles).toContain("@supports (height: env(safe-area-inset-top))");
    expect(styles).toContain("--mobile-header-offset: calc(51px + env(safe-area-inset-top, 0px));");
    expect(styles).toContain("padding: calc(4px + env(safe-area-inset-top, 0px)) 14px 8px;");
    expect(styles).toContain("body::before");
    expect(styles).toContain("height: env(safe-area-inset-top)");
    expect(styles).toContain("body.header-at-top::before");
    expect(styles).toContain("background: rgba(255, 253, 249, 0.98);");
    expect(styles).not.toContain("rgba(221, 104, 133, 0.36) 0%");
    expect(styles).not.toContain("padding-top: max(14px, env(safe-area-inset-top))");
    expect(styles).toContain("body.header-scrolled::before");
    expect(styles).toContain(".brand-header--at-top,\n  .brand-header--scrolled");
    expect(styles).toContain("border-radius: 0;");
    expect(styles).toContain("padding-top: var(--mobile-header-offset);");
    expect(styles).toContain("--mobile-header-offset: calc(45px + env(safe-area-inset-top, 0px));");
  });

  it("includes the locked S3 header and hero visual rules", () => {
    expect(styles).toContain("--color-sage-accent");
    expect(styles).toContain("--color-sage-accent: #adba85;");
    expect(styles).toContain("--font-cta:");
    expect(styles).toContain("--hero-overlay-bottom");
    expect(styles).toContain("--hero-button-offset: 4px;");
    expect(styles).toContain("--hero-copy-gap: 20px;");
    expect(styles).toContain("--hero-copy-top: clamp(58px, 8vh, 84px);");
    expect(styles).toContain("--hero-mobile-min-height: clamp(520px, 68vh, 640px);");
    expect(styles).toContain(".brand-header--at-top");
    expect(styles).toContain(".brand-header--scrolled");
    expect(styles).toContain("border-radius: 8px;");
    expect(styles).toContain("position: fixed;");
    expect(styles).toContain("backdrop-filter: blur(14px);");
    expect(styles).toContain("background-image: url(\"/assets/hero-s3-summer.png\")");
    expect(styles).toContain(".hero-photo__hand {\n  display: none;");
    expect(styles).toContain(".hero-section::after");
    expect(styles).toContain("min-height: var(--hero-mobile-min-height)");
    expect(styles).toContain("min-height: var(--hero-mobile-min-height, clamp(520px, 68vh, 640px))");
    expect(styles).toContain("scroll-padding-top: 84px");
    expect(styles).toContain("justify-self: center");
    expect(styles).toContain("max-height: min(650px, calc(94vh - 108px))");
    expect(styles).toContain("width: min(100%, 520px)");
    expect(styles).not.toContain(".hero-copy h1::after");
    expect(styles).not.toContain("86px 1px");
    expect(styles).toContain(".hero-section {\n  display: grid;");
    expect(styles).toContain("padding: 0;");
    expect(styles).toContain("border-radius: 0;");
    expect(styles).toContain("grid-template-columns: 40px minmax(0, 1fr) 40px;");
    expect(styles).toContain("grid-column: 2;");
    expect(styles).toContain("font-size: 21px;");
    expect(styles).toContain("font-family: var(--font-cta);");
    expect(styles).toContain(".brand-header--scrolled .brand-header__icon-button");
    expect(styles).toContain("background: transparent;");
    expect(styles).toContain("bottom: -1px;");
    expect(styles).toContain("height: clamp(180px, 32vh, 220px);");
    expect(styles).toContain("left: 0;");
    expect(styles).toContain("position: absolute;");
    expect(styles).toContain("right: 0;");
    expect(styles).toContain("border-radius: 0;");
    expect(styles).not.toContain(".hero-section::after,\n  .hero-copy,\n  .hero-photo");
    expect(styles).toContain("@media (max-width: 720px)");
    expect(styles).toContain("height: 105px;");
    expect(styles).toContain("rgba(251, 246, 238, 0.04) 18%");
    expect(styles).toContain("rgba(251, 246, 238, 0.14) 35%");
    expect(styles).toContain("rgba(251, 246, 238, 0.34) 55%");
    expect(styles).toContain("rgba(251, 246, 238, 0.68) 78%");
    expect(styles).toContain("#fbf6ee 100%");
  });

  it("includes dedicated layout tightening for 320px screens", () => {
    expect(styles).toContain("@media (max-width: 360px)");
    expect(styles).toContain(".product-carousel");
    expect(styles).toContain("grid-auto-columns: minmax(206px, 252px)");
    expect(styles).toContain(".hero-photo");
    expect(styles).toContain("grid-template-areas: \"hero\"");
    expect(styles).toContain(".hero-copy");
    expect(styles).toContain("z-index: 1");
    expect(styles).toContain(".confidence-carousel");
    expect(styles).not.toContain(".confidence-carousel__button");
    expect(styles).toContain("align-self: start;");
    expect(styles).toContain("padding: var(--hero-copy-top) clamp(24px, 6vw, 42px) 0;");
    expect(styles).toContain("gap: var(--hero-copy-gap);");
    expect(styles).toContain("margin-top: var(--hero-button-offset);");
    expect(styles).toContain("--hero-mobile-min-height: 540px;");
    expect(styles).toContain(".confidence-section {\n  background:");
    expect(styles).toContain("margin-top: 0;");
    expect(styles).toContain("padding: 26px 0 0;");
    expect(styles).toContain("padding: 28px 0 0;");
    expect(styles).not.toContain("margin-top: clamp(-32px, -5vw, -18px)");
    expect(styles).not.toContain("margin-top: -22px");
    expect(styles).not.toContain("margin-top: -18px");
    expect(styles).toContain("--hero-overlay-bottom: rgba(255, 250, 248, 0.58);");
    expect(styles).not.toContain("rgba(255, 250, 248, 0.44) 84%");
    expect(styles).not.toContain(".confidence-section::before");
    expect(styles).not.toContain(".confidence-section::after");
    expect(styles).not.toContain("top: clamp(-52px, -7vw, -34px)");
    expect(styles).not.toContain("height: 72px");
    expect(styles).not.toContain("height: clamp(82px, 12vw, 120px)");
    expect(styles).toContain("padding: 28px 0 clamp(24px, 6vw, 46px);");
    expect(styles).toContain("linear-gradient(180deg, #fbf6ee 0%, #fbf6ee 34%, #f7f0e6 100%)");
    expect(styles).not.toContain("backdrop-filter: blur(18px) saturate(1.05)");
    expect(styles).not.toContain("backdrop-filter: blur(12px) saturate(1.03)");
    expect(styles).not.toContain("rgba(255, 253, 249, 0.55) 28%");
    expect(styles).not.toContain("rgba(255, 253, 249, 0.9) 68%");
    expect(styles).not.toContain("0 14px 26px rgba(93, 48, 67, 0.07)");
    expect(styles).not.toContain("0 18px 38px rgba(93, 48, 67, 0.12)");
    expect(styles).not.toContain("0 1px 0 rgba(255, 255, 255, 0.7) inset");
    expect(styles).toContain("z-index: 1;");
    expect(styles).toContain(".confidence-carousel__viewport");
    expect(styles).toContain(".confidence-carousel__viewport::after");
    expect(styles).toContain("height: 52px;");
    expect(styles).toContain("height: 34px;");
    expect(styles).toContain("rgba(251, 246, 238, 0.75) 55%");
    expect(styles).toContain(".confidence-carousel__controls");
    expect(styles).toContain("padding: 8px 0 34px;");
    expect(styles).toContain("padding: 2px 0 24px;");
    expect(styles).toContain("0 10px 20px rgba(92, 65, 50, 0.055),\n    0 3px 8px rgba(92, 65, 50, 0.035)");
    expect(styles).not.toContain("mask-image: linear-gradient(");
    expect(styles).toContain(".confidence-carousel:focus-visible");
    expect(styles).not.toContain(".confidence-card--peek");
    expect(styles).toContain(".confidence-carousel__track");
    expect(styles).toContain("-webkit-overflow-scrolling: touch;");
    expect(styles).not.toMatch(/\.confidence-carousel__track\s*\{[^}]*scroll-snap-type: x mandatory;/);
    expect(styles).toContain("scroll-snap-type: none;");
    expect(styles).not.toContain(".confidence-carousel--auto-paused .confidence-carousel__track");
    expect(styles).toContain(".confidence-carousel--interacting .confidence-carousel__track");
    expect(styles).toContain("@media (prefers-reduced-motion: reduce)");
    expect(styles).toContain("scroll-padding-inline");
    expect(styles).toContain("padding: 10px max(32px, calc((100vw - var(--confidence-card-width)) / 2)) 52px;");
    expect(styles).toContain("padding: 6px max(30px, calc((100vw - var(--confidence-card-width)) / 2)) 34px;");
    expect(styles).not.toContain("--confidence-card-height");
    expect(styles).not.toContain(".confidence-carousel[data-track-index=\"1\"] .confidence-carousel__track");
    expect(styles).not.toContain("margin-left: calc(-100% + var(--confidence-peek) - var(--confidence-gap))");
    expect(styles).toContain("cursor: grab;");
    expect(styles).not.toContain(".confidence-carousel--dragging");
    expect(styles).toContain("cursor: grabbing;");
    expect(styles).toContain("touch-action: pan-x pan-y;");
    expect(styles).not.toMatch(/\.collection-track\s*\{[^}]*scroll-snap-type: x mandatory;/);
    expect(styles).not.toContain("animation: confidence-loop");
    expect(styles).not.toContain(".confidence-carousel--paused .confidence-carousel__track");
    expect(styles).not.toContain("animation-play-state: paused;");
    expect(styles).not.toContain("@keyframes confidence-loop");
    expect(styles).not.toContain(".confidence-carousel__track--resetting");
    expect(styles).toContain("overflow: visible;");
    expect(styles).toContain(".collection-card__visual");
    expect(styles).toContain("padding: 14px 14px 22px;");
    expect(styles).toContain("--confidence-card-width: min(80vw, 306px);");
    expect(styles).toContain("--confidence-card-width: min(78vw, 282px);");
    expect(styles).toContain("min-height: 154px;");
    expect(styles).toContain("min-height: 148px;");
    expect(styles).not.toContain(".confidence-card__visual");
    expect(styles).not.toContain(".confidence-card__visual--wear");
    expect(styles).not.toContain(".confidence-card__visual--hand");
    expect(styles).not.toContain(".confidence-card__visual-frame");
    expect(styles).not.toContain(".confidence-card__tray");
    expect(styles).not.toContain(".confidence-card__glue");
    expect(styles).not.toContain(".confidence-card__hand");
    expect(styles).not.toContain(".confidence-card__copy");
    expect(styles).not.toContain(".confidence-card__body");
    expect(styles).not.toContain(".confidence-card__number");
    expect(styles).toContain(".confidence-progress");
    expect(styles).not.toContain(".confidence-dots");
    expect(styles).toContain(".collection-carousel__hint");
    expect(styles).toContain(".collection-products");
    expect(styles).toContain(".collection-product-row");
    expect(styles).toContain("margin-inline: calc(-1 * clamp(18px, 4vw, 56px));");
    expect(styles).toContain("max-width: none;");
    expect(styles).toContain("padding: 2px 18px 12px;");
    expect(styles).toContain("scroll-padding-inline: 18px;");
    expect(styles).toContain("grid-auto-columns: minmax(132px, 42vw);");
    expect(styles).toContain("grid-template-columns: repeat(2, 170px);");
    expect(styles).toContain("column-gap: 20px;");
    expect(styles).toContain("justify-content: center;");
    expect(styles).toContain("row-gap: 20px;");
    expect(styles).toContain("height: 245px;");
    expect(styles).toContain(".collection-product-teaser");
    expect(styles).toContain("height: 70px;");
    expect(styles).toContain(".collection-product-teaser {\n  column-gap: 20px;");
    expect(styles).toContain("height: 70px;\n  justify-content: center;\n  margin-top: 6px;");
    expect(styles).toContain("linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, #ffffff 88%)");
    expect(styles).toContain(".collection-products__more");
    expect(styles).toContain(".collection-products__more {\n  align-self: center;");
    expect(styles).toContain("justify-content: center;\n  margin-top: 6px;");
    expect(styles).not.toContain("grid-auto-columns: minmax(148px, 56vw);");
    expect(styles).not.toContain(".confidence-carousel__hint");
    expect(styles).toContain("margin-top: 14px;");
    expect(styles).toContain("scrollbar-width: none");
    expect(styles).not.toContain(".shop-more-grid");
    expect(styles).not.toContain(".weekly-set-section");
    expect(styles).toContain(".review-proof-row {\n    flex-wrap: wrap;");
    expect(styles).toContain(".collection-section {\n    padding-bottom: 24px;");
    expect(styles).toContain(".collection-carousel {\n    margin-inline: -14px;");
    expect(styles).toContain(".collection-products,\n  .collection-products__heading {\n    min-width: 0;");
    expect(styles).toContain(".collection-product-row,\n  .collection-product-teaser {\n    grid-template-columns: repeat(2, minmax(0, 1fr));");
    expect(styles).toContain(".collection-products__more {\n    max-width: 100%;\n    justify-self: center;\n    width: fit-content;");
    expect(styles).toContain(".review-carousel {\n    gap: 8px;");
    expect(styles).toContain(".review-card--peek {\n    display: none;");
    expect(styles).toContain(".kit-spread {\n    min-height: 250px;");
    expect(styles).toContain(".kit-spread {\n    min-height: 238px;");
    expect(styles).not.toContain("min-height: 166px;");
    expect(styles).not.toContain("min-height: 158px;");
    expect(styles).toContain("position: static;");
    expect(styles).toContain("font-size: 1.8rem");
    expect(styles).toContain("padding: 28px 0 0");
  });

  it("does not force tiny mobile viewports wider than the screen", () => {
    expect(styles).not.toContain("min-width: 320px");
    expect(styles).toContain("min-width: 0");
    expect(styles).toContain(".site-footer {\n    padding: 26px 14px 24px;");
  });

  it("keeps the bare-bones mobile hero copy compact for structure review", () => {
    expect(styles).toContain("--barebones-mobile-header-offset: 45px;");
    expect(styles).toContain("--barebones-hero-section-height: 635px;");
    expect(styles).toContain("--barebones-hero-copy-top: 23px;");
    expect(styles).toContain("--barebones-hero-copy-inline: 29px;");
    expect(styles).toContain("--barebones-hero-copy-bottom: 1px;");
    expect(styles).toContain("--barebones-hero-copy-height: 263.36px;");
    expect(styles).toContain("@media (max-width: 720px) {");
    expect(styles).toContain(".storefront-barebones .hero-copy {\n    height: var(--barebones-hero-copy-height);");
    expect(styles).toContain(
      "padding: var(--barebones-hero-copy-top) var(--barebones-hero-copy-inline) var(--barebones-hero-copy-bottom);"
    );
    expect(styles).toContain("height: var(--barebones-hero-copy-height);");
    expect(styles).toContain(".storefront-barebones .hero-section {\n    height: var(--barebones-hero-section-height);");
    expect(styles).toContain("padding-top: var(--barebones-mobile-header-offset);");
    expect(styles).toContain(".hero-photo--asset-preserved::before");
    expect(styles).toContain("border-color: transparent !important;");
  });

  it("sizes the bare-bones How It Works heading from mobile review tokens", () => {
    expect(styles).toContain("--barebones-confidence-heading-height: 85.06px;");
    expect(styles).toContain("--barebones-confidence-eyebrow-height: 20.48px;");
    expect(styles).toContain("--barebones-confidence-eyebrow-offset: -3px;");
    expect(styles).toContain(".storefront-barebones .confidence-section__heading {\n    height: var(--barebones-confidence-heading-height);");
    expect(styles).toContain(".storefront-barebones .confidence-section__heading .eyebrow");
    expect(styles).toContain("height: var(--barebones-confidence-eyebrow-height);");
    expect(styles).toContain("line-height: var(--barebones-confidence-eyebrow-height);");
    expect(styles).toContain("transform: translateY(var(--barebones-confidence-eyebrow-offset));");
  });

  it("keeps bare-bones header action buttons white without circular outlines", () => {
    expect(styles).toContain("--barebones-mobile-brand-size: 25px;");
    expect(styles).toContain(".site-shell--barebones .brand-mark {\n    font-size: var(--barebones-mobile-brand-size);");
    expect(styles).toContain(".site-shell--barebones .brand-header {\n  border-color: transparent !important;");
    expect(styles).toContain(".site-shell--barebones .brand-header__icon-button");
    expect(styles).toContain("background: #ffffff !important;");
    expect(styles).toContain("border-color: transparent !important;");
    expect(styles).toContain("color: #000000 !important;");
    expect(styles).toContain(
      ".site-shell--barebones .brand-header__icon-button svg,\n.site-shell--barebones .brand-header__icon-button svg *"
    );
    expect(styles).toContain("stroke: #000000 !important;");
    expect(styles).toContain(".storefront-barebones .kit-primary-link,\n.storefront-barebones .kit-primary-link span");
    expect(styles).toContain("color: #ffffff !important;");
  });

  it("keeps the What’s Included kit image frameless and visually larger", () => {
    expect(styles).toContain(".kit-spread {\n  align-items: center;");
    expect(styles).toContain("border: 0;");
    expect(styles).toContain("padding: 0;");
    expect(styles).toContain(".kit-spread__image");
    expect(styles).toContain("object-fit: cover;");
    expect(styles).not.toContain(".collection-card__mood,\n.kit-spread,\n.review-product__art");
  });

  it("includes compact mobile header rules that hide the desktop nav", () => {
    expect(styles).toContain(".brand-header__mobile-actions");
    expect(styles).toContain(".brand-header__desktop-nav");
    expect(styles).toContain(".brand-header__mobile-menu");
    expect(styles).toContain("@media (max-width: 720px)");
    expect(styles).toContain(".brand-header__desktop-nav {\n    display: none;");
    expect(styles).toContain(".brand-header__mobile-actions {\n    display: contents;");
    expect(styles).toContain(".brand-header__mobile-menu {\n    display: grid;");
  });
});
